"""
Emotional Map of Brighton - интерактивный дашборд.

Запуск:
    PYTHONPATH=src .venv/bin/streamlit run app/streamlit_app.py

=== ПРО ЯЗЫК ===
Интерфейс английский: репозиторий и README на GitHub английские, и
дашборд должен читаться теми же людьми. Комментарии в коде остаются
русскими - это рабочий язык автора, а не язык публикации.

Подписи карты берутся из src/bem/viz/labels.py через DASHBOARD_LANG,
чтобы карта внутри дашборда не разъезжалась с остальным интерфейсом.

=== ПРИНЦИПЫ, ПО КОТОРЫМ СДЕЛАН ЭТОТ ДАШБОРД ===

1. Дашборд НИЧЕГО НЕ СЧИТАЕТ ТЯЖЁЛОГО.
   Он читает готовые файлы из data/processed. Все модели отработали
   заранее, в скриптах. Если запускать DistilBERT при каждом движении
   ползунка, интерфейс будет думать по полминуты, и им никто не станет
   пользоваться. Разделение "тяжёлый счёт офлайн, дашборд только
   показывает" - базовое правило продуктовой аналитики.

2. Кэширование обязательно.
   @st.cache_data означает: результат функции запоминается, и при
   следующем перерисовывании (а Streamlit перезапускает весь скрипт
   на КАЖДОЕ действие пользователя) файл с диска читается не заново.

3. Число наблюдений показывается всегда.
   Если после фильтров осталось 12 текстов, пользователь должен это
   видеть, а не гадать, почему график странный.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Чтобы работал импорт bem/ при запуске через streamlit run
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd
import plotly.express as px
import streamlit as st
from streamlit.components.v1 import html as st_html

from bem.config import PROCESSED_DIR
from bem.geo.districts import district_colors, district_names
from bem.viz.labels import get_months
from bem.viz.maps import add_title, build_map

st.set_page_config(page_title="Emotional Map of Brighton", page_icon="🌊", layout="wide")

# Язык дашборда задаётся здесь один раз и передаётся в build_map.
DASHBOARD_LANG = "en"

MONTHS = get_months(DASHBOARD_LANG)

# Порог, ниже которого точке на графике верить не стоит.
MIN_OBSERVATIONS = 20


# ------------------------------------------------------------ загрузка ----

@st.cache_data
def load_texts() -> pd.DataFrame:
    df = pd.read_csv(PROCESSED_DIR / "texts_final.csv", parse_dates=["created_utc"])
    df["month"] = df["created_utc"].dt.to_period("M").dt.to_timestamp()
    df["district_name"] = df["district"].map(district_names())
    return df


@st.cache_data
def load_places() -> pd.DataFrame:
    path = PROCESSED_DIR / "place_summary.csv"
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


@st.cache_data
def load_police() -> pd.DataFrame:
    """Реальные происшествия Police.uk. Файла может не быть - это не ошибка."""
    path = PROCESSED_DIR / "police_incidents.csv"
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path)
    df["month_dt"] = pd.to_datetime(df["month"])
    df["month_num"] = df["month_dt"].dt.month
    df["district_name"] = df["district"].map(district_names())
    return df


def net_sentiment(labels: pd.Series) -> float:
    """Доля позитива минус доля негатива."""
    if len(labels) == 0:
        return 0.0
    return (labels == "pos").mean() - (labels == "neg").mean()


def thousands(n: int) -> str:
    """Разделитель разрядов - неразрывный пробел, как принято в отчётах."""
    return f"{n:,}".replace(",", " ")


# ------------------------------------------------------------ интерфейс ----

texts = load_texts()
places = load_places()

st.title("🌊 Emotional Map of Brighton")

# ---------- фильтры ----------
with st.sidebar:
    st.header("Filters")

    min_date = texts["created_utc"].min().date()
    max_date = texts["created_utc"].max().date()
    date_range = st.slider(
        "Period", min_value=min_date, max_value=max_date,
        value=(min_date, max_date), format="MMM YYYY",
    )

    all_districts = sorted(texts["district_name"].dropna().unique())
    chosen_districts = st.multiselect("Districts", all_districts, default=all_districts)

    all_categories = sorted(texts["category"].dropna().unique())
    chosen_categories = st.multiselect(
        "Venue type", all_categories, default=all_categories,
        help="Selecting specific categories drops texts that are not linked "
             "to a venue at all.",
    )

    all_topics = sorted(texts["topic"].dropna().unique())
    chosen_topics = st.multiselect("Topics", all_topics, default=all_topics)

    st.divider()

    # Источники данных. Про синтетические тексты сказано здесь, а не
    # плашкой на главном экране: предупреждение нужно, но кричать им
    # на весь дашборд незачем.
    if (texts["source"] == "demo").all():
        st.caption(
            "Sources: OpenStreetMap (ODbL), Police.uk (OGL v3.0). "
            "The texts are synthetic, generated by "
            "`src/bem/collect/demo_corpus.py` for pipeline development. "
            "The \"Real data\" tab is built on genuine records."
        )
    else:
        st.caption(
            "Sources: OpenStreetMap (ODbL), Reddit, Police.uk (OGL v3.0)."
        )

    st.caption(
        "All models ran ahead of time - this dashboard only displays results."
    )

# ---------- применяем фильтры ----------
mask = (
    (texts["created_utc"].dt.date >= date_range[0])
    & (texts["created_utc"].dt.date <= date_range[1])
    & (texts["district_name"].isin(chosen_districts))
    & (texts["topic"].isin(chosen_topics))
)
if chosen_categories and len(chosen_categories) < len(all_categories):
    mask &= texts["category"].isin(chosen_categories)

view = texts[mask]

if view.empty:
    st.error("No texts left after filtering. Loosen the filters on the left.")
    st.stop()

# ---------- ключевые цифры ----------
c1, c2, c3, c4 = st.columns(4)
c1.metric("Texts", thousands(len(view)))
c2.metric("Net sentiment", f"{net_sentiment(view['sentiment_label']):+.3f}",
          help="Share of positive minus share of negative texts. Ranges from -1 to +1.")
c3.metric("Positive", f"{(view['sentiment_label'] == 'pos').mean():.0%}")
c4.metric("Districts in view", view["district"].nunique())

if len(view) < 100:
    st.info(
        f"Only {len(view)} texts in the current selection - too few for stable "
        "conclusions. The charts below will be noisy.", icon="ℹ️",
    )

police = load_police()

tab_map, tab_time, tab_topics, tab_places, tab_texts, tab_police = st.tabs(
    ["🗺 Map", "📈 Trends", "🏷 Topics", "📍 Venues", "💬 Texts", "🚓 Real data"]
)

# ---------- карта ----------
with tab_map:
    summary = (
        view.groupby("district")
        .agg(n=("sentiment_label", "size"),
             net_sentiment=("sentiment_label", net_sentiment),
             share_pos=("sentiment_label", lambda s: (s == "pos").mean()),
             share_neg=("sentiment_label", lambda s: (s == "neg").mean()))
    )
    summary["name"] = [district_names().get(i, i) for i in summary.index]

    m = build_map(summary, texts=view, places=places if len(places) else None,
                  lang=DASHBOARD_LANG)
    add_title(m, "Sentiment by district",
              f"{len(view)} texts · layers can be toggled in the top right corner")
    st_html(m.get_root().render(), height=560)

    st.dataframe(
        summary[["name", "n", "net_sentiment", "share_pos", "share_neg"]]
        .rename(columns={"name": "District", "n": "Texts",
                         "net_sentiment": "Net sentiment",
                         "share_pos": "Share positive", "share_neg": "Share negative"})
        .sort_values("Net sentiment", ascending=False),
        use_container_width=True, hide_index=True,
    )

# ---------- динамика ----------
with tab_time:
    monthly = (
        view.groupby(["month", "district_name"])
        .agg(net=("sentiment_label", net_sentiment), n=("sentiment_label", "size"))
        .reset_index()
    )

    fig = px.line(
        monthly, x="month", y="net", color="district_name", markers=True,
        color_discrete_map={district_names()[k]: v for k, v in district_colors().items()
                            if k in district_names()},
        labels={"month": "", "net": "Net sentiment", "district_name": "District"},
        title="Monthly sentiment",
    )
    fig.add_hline(y=0, line_dash="dash", line_color="#aaa")
    fig.update_layout(height=430, hovermode="x unified")
    st.plotly_chart(fig, use_container_width=True)

    seasonal = view.copy()
    seasonal["month_num"] = seasonal["created_utc"].dt.month
    prof = (
        seasonal.groupby(["month_num", "district_name"])
        .agg(net=("sentiment_label", net_sentiment)).reset_index()
    )
    prof["Month"] = prof["month_num"].apply(lambda m: MONTHS[m - 1])

    fig2 = px.line(
        prof.sort_values("month_num"), x="Month", y="net", color="district_name",
        markers=True, labels={"net": "Net sentiment", "district_name": "District"},
        title="Average yearly profile (all years combined)",
    )
    fig2.add_vrect(x0=6.6, x1=7.4, fillcolor="#ffd54f", opacity=0.3, line_width=0,
                   annotation_text="Pride")
    fig2.add_vrect(x0=3.6, x1=4.4, fillcolor="#90caf9", opacity=0.3, line_width=0,
                   annotation_text="Fringe")
    fig2.add_hline(y=0, line_dash="dash", line_color="#aaa")
    fig2.update_layout(height=430)
    st.plotly_chart(fig2, use_container_width=True)

    low = monthly[monthly["n"] < MIN_OBSERVATIONS]
    if len(low):
        st.caption(
            f"⚠️ {len(low)} of {len(monthly)} points are based on fewer than "
            f"{MIN_OBSERVATIONS} texts each and should not be trusted."
        )

# ---------- темы ----------
with tab_topics:
    topic_district = (
        view.groupby(["district_name", "topic"])
        .size().reset_index(name="n")
    )
    topic_district["share"] = topic_district.groupby("district_name")["n"].transform(
        lambda s: s / s.sum()
    )

    fig = px.bar(
        topic_district, x="share", y="district_name", color="topic",
        orientation="h", labels={"share": "Share of texts", "district_name": "",
                                 "topic": "Topic"},
        title="What people write about in each district",
    )
    fig.update_layout(height=420, xaxis_tickformat=".0%")
    st.plotly_chart(fig, use_container_width=True)

    topic_sent = (
        view.groupby("topic")
        .agg(net=("sentiment_label", net_sentiment), n=("sentiment_label", "size"))
        .reset_index().sort_values("net")
    )
    fig2 = px.bar(
        topic_sent, x="net", y="topic", orientation="h", color="net",
        color_continuous_scale=["#d32f2f", "#fdd835", "#2e7d32"],
        color_continuous_midpoint=0, text="n",
        labels={"net": "Net sentiment", "topic": ""},
        title="Which topics draw praise and which draw complaints "
              "(number = text count)",
    )
    fig2.update_layout(height=420, coloraxis_showscale=False)
    st.plotly_chart(fig2, use_container_width=True)

# ---------- заведения ----------
with tab_places:
    if places.empty:
        st.info("No place_summary.csv found - run scripts/06_build_outputs.py")
    else:
        st.markdown(
            "Scores are **shrunk toward the city-wide mean** in proportion to "
            "the number of mentions. Without this, the top of the list fills up "
            "with venues that have three random reviews and a \"perfect\" score "
            "of 1.00. `confidence` shows how much of the score comes from the "
            "venue's own data rather than from the global mean."
        )
        show = places[places["district"].isin(
            [k for k, v in district_names().items() if v in chosen_districts]
        )]
        cols = ["name", "district", "category", "n_texts",
                "net_sentiment", "net_sentiment_shrunk", "confidence"]
        cols = [c for c in cols if c in show.columns]

        c1, c2 = st.columns(2)
        with c1:
            st.subheader("Highest rated")
            st.dataframe(show.nlargest(15, "net_sentiment_shrunk")[cols],
                         use_container_width=True, hide_index=True)
        with c2:
            st.subheader("Lowest rated")
            st.dataframe(show.nsmallest(15, "net_sentiment_shrunk")[cols],
                         use_container_width=True, hide_index=True)

# ---------- тексты ----------
with tab_texts:
    st.caption(
        "A random sample, so the labelling can be checked by eye. This step is "
        "not optional: metrics fail more quietly than raw text does."
    )
    polarity = st.radio("Show", ["all", "pos", "neu", "neg"], horizontal=True)

    sample = view if polarity == "all" else view[view["sentiment_label"] == polarity]
    if sample.empty:
        st.info("No texts of that kind in the current selection.")
    else:
        st.dataframe(
            sample.sample(min(40, len(sample)), random_state=0)[
                ["created_utc", "district_name", "topic", "sentiment_label",
                 "sentiment_score", "text"]
            ].sort_values("created_utc")
            .rename(columns={"created_utc": "date", "district_name": "district"}),
            use_container_width=True, hide_index=True,
        )

# ---------- реальные данные Police.uk ----------
with tab_police:
    if police.empty:
        st.info(
            "No police_incidents.csv found - run "
            "`PYTHONPATH=src .venv/bin/python scripts/07_collect_police.py`. "
            "No API keys required."
        )
    else:
        st.success(
            f"**This is real data.** {thousands(len(police))} incidents across "
            f"{police['month'].nunique()} months from the Police.uk API "
            f"(Open Government Licence). Unlike the tabs above, nothing here "
            f"is synthetic.",
            icon="✅",
        )
        st.caption(
            "Read with care: the number of *recorded* incidents is not the crime "
            "rate. It is the crime rate multiplied by willingness to report and "
            "by police presence. Police.uk also snaps coordinates to street "
            "centroids for victim privacy."
        )

        only_atmosphere = st.checkbox(
            "Only categories that shape a district's atmosphere",
            value=True,
            help="anti-social-behaviour, public-order, violent-crime, "
                 "criminal-damage-arson, drugs, possession-of-weapons. "
                 "Shoplifting is excluded: it says more about retail than "
                 "about what a place feels like.",
        )

        pol = police[police["district"] != "other"]
        if only_atmosphere:
            pol = pol[pol["is_atmosphere"]]

        # Нормируем на средний месяц САМОГО района - иначе график покажет
        # только то, что один район больше другого.
        per_month = (
            pol.groupby(["district_name", "month_num"])
            .agg(n=("crime_id", "size"), months=("month", "nunique"))
            .reset_index()
        )
        per_month["avg"] = per_month["n"] / per_month["months"]
        per_month["norm"] = per_month.groupby("district_name")["avg"].transform(
            lambda s: s / s.mean()
        )
        per_month["Month"] = per_month["month_num"].apply(lambda m: MONTHS[m - 1])

        fig = px.line(
            per_month.sort_values("month_num"), x="Month", y="norm",
            color="district_name", markers=True,
            labels={"norm": "level relative to a normal month",
                    "district_name": "District"},
            title="Seasonality of incidents (1.0 = a normal month for that district)",
        )
        fig.add_hline(y=1.0, line_dash="dash", line_color="#aaa")
        fig.add_vrect(x0=6.6, x1=7.4, fillcolor="#ffd54f", opacity=0.3,
                      line_width=0, annotation_text="Pride")
        fig.add_vrect(x0=3.6, x1=4.4, fillcolor="#90caf9", opacity=0.3,
                      line_width=0, annotation_text="Fringe")
        fig.update_layout(height=450, hovermode="x unified")
        st.plotly_chart(fig, use_container_width=True)

        st.markdown(
            "**A finding that refuted the original assumption.** The demo corpus "
            "was built with August as the year's main peak. Real data shows the "
            "peak falls in **July** for four districts out of five. The one "
            "exception is **Seafront** - exactly the geography the Brighton "
            "Pride parade runs through."
        )

        c1, c2 = st.columns(2)
        with c1:
            st.subheader("Peak month by district")
            peaks = (
                per_month.loc[per_month.groupby("district_name")["norm"].idxmax()]
                [["district_name", "Month", "norm"]]
                .rename(columns={"district_name": "District",
                                 "norm": "Peak level"})
                .sort_values("Peak level", ascending=False)
            )
            st.dataframe(peaks, use_container_width=True, hide_index=True)
        with c2:
            st.subheader("Incident categories")
            cats = (
                police[police["district"] != "other"]["category"]
                .value_counts().head(10).reset_index()
            )
            cats.columns = ["Category", "Count"]
            st.dataframe(cats, use_container_width=True, hide_index=True)
